import Head from "next/head";
import { useState } from "react";
import MainLayout from "../../components/MainLayout";
import Title from "../../components/Title";
import styled from 'styled-components';

const Text = styled.textarea`
background: none;
color: inherit;
border: none;
border-bottom: 1px solid #fff;
height: 300px;
width: 100%;
`;

const Form = styled.form`
width: 400px;
display: flex;
flex-direction: column;
align-items: center;
`;

const Result = styled.p`
font-size: 1.5em;
`;

const fetcher = (...args) => fetch(...args).then((res) => res.json());

export default function Home() {
    const [data, setData] = useState({});
    const submitQuery = (e) => {
        e.preventDefault();
        const promptText = e.target[0].value;
        fetcher(`/api/weapon?promptText=${promptText}`).then((d) => setData(d));
    }
    return (
        <MainLayout>
            <Head>
                <title>Weapon Generator</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Title>Magical Weapon Generator</Title>

            <p>
                This page uses GPT-3 to generate magical weapons based on a prompt.
            </p>
            <Form onSubmit={submitQuery}>
                <Text placeholder="A magical greatsword that allows the user to cast fireball as an action" />
                <button>Generate</button>
            </Form>
            <Result>
                {data?.choices?.[0]?.text.split("\n").map((line) => (<>{line} <br /></>))}
            </Result>
        </MainLayout>
    );
}
