import Head from "next/head";
import Link from "next/link";
import useSWR, { SWRConfig } from "swr";
import { getResourcesFromAirtable } from "../airtable";
import MainLayout from "../components/MainLayout";
import Title from "../components/Title";

const fetcher = (...args) => fetch(...args).then((res) => res.json());

export async function getStaticProps() {
  // `getStaticProps` is executed on the server side.
  const resources = await getResourcesFromAirtable();
  return {
    props: {
      fallback: {
        "/api/resources": resources,
      },
    },
  };
}

function Resources() {
  const { data, error } = useSWR("/api/resources", fetcher);
  return (
    <MainLayout>
      <Head>
        <title>Has Been Wizards</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Title>Awesome DM Resources</Title>
      <p>
        This is a place to find resources to become a better game master and
        worldbuilder.
        <h2>Resources</h2>
        <ul>
          {data.map((resource, i) => {
            return (
              <li key={i}>
                <h3>
                  <Link href={resource.Link}>{resource.Name}</Link>
                </h3>
                <p>{resource.Notes}</p>
              </li>
            );
          })}
        </ul>
      </p>
    </MainLayout>
  );
}

export default function Page({ fallback }) {
  // SWR hooks inside the `SWRConfig` boundary will use those values.
  return (
    <SWRConfig value={{ fallback }}>
      <Resources />
    </SWRConfig>
  );
}
